### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by aliafshany** [wifiuk/NordLynx-WireGuard-Config-Extract#1]
hi
thanks for this script.
i would like to know if this extractor works with linux nordvpn-cli or not.
best

**Comment by wifiuk** [comment]
yes it does

**Comment by aliafshany** [comment]
hi agin
i get this error:

sudo: unable to execute ./NordLynxExtractKeys.sh: Invalid argument
i have done the steps.


Update: it works with "sudo bash NordLynxExtractKeys.sh uk"

best

**Comment by wifiuk** [comment]
Glad you sorted it
